### PR TITLE
Data indication arrows fix

### PR DESCRIPTION
**Pull request by HardLight**
This is attempt to fix missing data indication arrows in status bar and quick settings.

### CODE REVIEW

**Comment by GarciaLnk** [comment]
I hope that this doesn't break anything :P

**Comment by HardLight** [comment]
@Garcia98 
I also hope that won't happen :D of course it can be reverted. If you could make test build for lotus I could check it.

**Comment by GarciaLnk** [comment]
@HardLight Here you have it: http://hubdroid.com:8989/job/xperiaste-cm11-xgo/ws/cm11_lotus-test.zip :smile:

**Comment by HardLight** [comment]
It's working :smile: 
screenshot_2014-11-26-15-52-34
screenshot_2014-11-26-16-00-48

**Comment by GarciaLnk** [comment]
Good :)

**Pull request merged**
